#ifndef __HOLLY_H
#define __HOLLY_H

// Internal to the HOLLY itself.
#define HOLLY_INTERNAL_IRQ_STATUS *((volatile uint32_t *)0xA05F6900)
#define HOLLY_INTERNAL_IRQ_2_MASK *((volatile uint32_t *)0xA05F6910)
#define HOLLY_INTERNAL_IRQ_4_MASK *((volatile uint32_t *)0xA05F6920)
#define HOLLY_INTERNAL_IRQ_6_MASK *((volatile uint32_t *)0xA05F6930)

#define HOLLY_INTERNAL_INTERRUPT_VIDEO_RENDER_FINISHED 0x00000001
#define HOLLY_INTERNAL_INTERRUPT_ISP_RENDER_FINISHED 0x00000002
#define HOLLY_INTERNAL_INTERRUPT_TSP_RENDER_FINISHED 0x00000004
#define HOLLY_INTERNAL_INTERRUPT_VBLANK_IN 0x00000008
#define HOLLY_INTERNAL_INTERRUPT_VBLANK_OUT 0x00000010
#define HOLLY_INTERNAL_INTERRUPT_HBLANK 0x00000020
#define HOLLY_INTERNAL_INTERRUPT_TRANSFER_YUV_FINISHED 0x00000040
#define HOLLY_INTERNAL_INTERRUPT_TRANSFER_OPAQUE_FINISHED 0x00000080
#define HOLLY_INTERNAL_INTERRUPT_TRANSFER_OPAQUE_MODIFIER_FINISHED 0x00000100
#define HOLLY_INTERNAL_INTERRUPT_TRANSFER_TRANSPARENT_FINISHED 0x00000200
#define HOLLY_INTERNAL_INTERRUPT_TRANSFER_TRANSPARENT_MODIFIER_FINISHED 0x00000400
#define HOLLY_INTERNAL_INTERRUPT_MAPLE_DMA_FINISHED 0x00001000
#define HOLLY_INTERNAL_INTERRUPT_MAPLE_VBLANK_FINISHED 0x00002000
#define HOLLY_INTERNAL_INTERRUPT_AICA_DMA_FINISHED 0x00008000
#define HOLLY_INTERNAL_INTERRUPT_TRANSFER_PUNCHTHRU_FINISHED 0x00200000
#define HOLLY_INTERNAL_INTERRUPT_CHECK_EXTERNAL 0x40000000
#define HOLLY_INTERNAL_INTERRUPT_CHECK_ERROR 0x80000000

#define HOLLY_INTERNAL_INTERRUPT_RENDER_FINISHED ( \
    HOLLY_INTERNAL_INTERRUPT_VIDEO_RENDER_FINISHED | \
    HOLLY_INTERNAL_INTERRUPT_ISP_RENDER_FINISHED | \
    HOLLY_INTERNAL_INTERRUPT_TSP_RENDER_FINISHED \
)
#define HOLLY_INTERNAL_INTERRUPT_TRANSFER_FINISHED ( \
    HOLLY_INTERNAL_INTERRUPT_TRANSFER_YUV_FINISHED | \
    HOLLY_INTERNAL_INTERRUPT_TRANSFER_OPAQUE_FINISHED | \
    HOLLY_INTERNAL_INTERRUPT_TRANSFER_OPAQUE_MODIFIER_FINISHED | \
    HOLLY_INTERNAL_INTERRUPT_TRANSFER_TRANSPARENT_FINISHED | \
    HOLLY_INTERNAL_INTERRUPT_TRANSFER_TRANSPARENT_MODIFIER_FINISHED | \
    HOLLY_INTERNAL_INTERRUPT_TRANSFER_PUNCHTHRU_FINISHED \
)

// Caused by external sources that HOLLY manages.
#define HOLLY_EXTERNAL_IRQ_STATUS *((volatile uint32_t *)0xA05F6904)
#define HOLLY_EXTERNAL_IRQ_2_MASK *((volatile uint32_t *)0xA05F6914)
#define HOLLY_EXTERNAL_IRQ_4_MASK *((volatile uint32_t *)0xA05F6924)
#define HOLLY_EXTERNAL_IRQ_6_MASK *((volatile uint32_t *)0xA05F6934)

#define HOLLY_EXTERNAL_INTERRUPT_DIMM_COMMS 0x00000008

// Errors that have happened in various pieces of hardware.
#define HOLLY_ERROR_IRQ_STATUS *((volatile uint32_t *)0xA05F6908)
#define HOLLY_ERROR_IRQ_2_MASK *((volatile uint32_t *)0xA05F6918)
#define HOLLY_ERROR_IRQ_4_MASK *((volatile uint32_t *)0xA05F6928)
#define HOLLY_ERROR_IRQ_6_MASK *((volatile uint32_t *)0xA05F6938)

#endif
